import { Geist, Geist_Mono,Poppins } from "next/font/google";
import "./globals.css";
import { Lato } from 'next/font/google';

const lato = Lato({
  weight: ['300', '400', '700'], // Choose the weights you need
  subsets: ['latin'],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ['300', '400', '600'],   
  subsets: ['latin'],              
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} poppins.className`}>
        {children}
      </body>
    </html>
  );
}
